### ISSUE TITLE
[BUG] [ANDROID/IOS] your issue....

### ISSUE THREAD

**Issue by Amrazyan** [Flucadetena/pedometer_2#2]
**Describe the bug**
Sometimes when listening to step changes, it can give some wrong values, and then make  corrections, for example
2024-6-23 12:17:09.300893
26485

2024-6-23 12:25:33.391574
26529

2024-6-23 12:25:33.391574
26533

2024-6-23 14:17:03.857615
26333

2024-6-23 14:33:55.859886
96784

2024-6-23 14:33:55.861243
26333
 It happens on both platforms android and ios

**Comment by Flucadetena** [comment]
Hey @Amrazyan thanks for creating the issue and using the plugin. That is very interesting. I haven't experience it or maybe I did not notice.

Could you share a bit more about the situation: your testing code; how you are testing it, android and ios configuration and versions,... anything you believe could be relevant to the problem.
So I can try and reproduce it.

Thanks in advance ;)

**Comment by Amrazyan** [comment]
Hi @Flucadetena  it happens on both ios and android , and Im using your example code sometimes its just lets say correcting values, here is another log, scoreIndex represents steps from _listenStepCountStream method
{"post":{"scoreIndex":"4778","todaySteps":"1560"},"timestamp":"2024-06-23 19:55:51"}
{"post":{"scoreIndex":"4778","todaySteps":"1560"},"timestamp":"2024-06-23 19:51:42"}
{"post":{"scoreIndex":"4778","todaySteps":"1560"},"timestamp":"2024-06-23 19:51:31"}
{"post":{"scoreIndex":"4778","todaySteps":"1560"},"timestamp":"2024-06-23 19:51:21"}
{"post":{"scoreIndex":"4778","todaySteps":"1560"},"timestamp":"2024-06-23 19:51:13"}
{"post":{"scoreIndex":"4743","todaySteps":"1525"},"timestamp":"2024-06-23 19:35:45"}
{"post":{"scoreIndex":"4934","todaySteps":"1525"},"timestamp":"2024-06-23 19:35:35"}
{"post":{"scoreIndex":"4924","todaySteps":"1515"},"timestamp":"2024-06-23 18:40:24"}
{"post":{"scoreIndex":"4924","todaySteps":"1515"},"timestamp":"2024-06-23 18:37:00"}
{"post":{"scoreIndex":"4924","todaySteps":"1515"},"timestamp":"2024-06-23 18:36:50"}
{"post":{"scoreIndex":"4924","todaySteps":"1515"},"timestamp":"2024-06-23 18:36:40"}

**Comment by Flucadetena** [comment]
Hi @Amrazyan I'll test it tomorrow and get back to you. Lets see if I can find a solution quickly.

I'll keep you posted.

**Comment by Amrazyan** [comment]
Thank you so much

**Comment by Flucadetena** [comment]
Hey @Amrazyan I've been working on it and I can't seem to reproduce the problem. There are a couple of things that caught my attention and you can help me understand better the tests to see if I can reproduce it. Do this please and I'll try again:

1.- Paste de code you are using, if it is the example app paste the whole "main.dart" in here between ```
2.- I've noticed that there is a big jump between the timestamps when the step fluctuation occurs. (from 20" to 1h+). Please explain to me very detailed how you are testing and getting the results. (Are you installing the app and walking with it during the day? Are you shacking the phone? Do you reset the phone or app between tests?) Give me as much detail as you can.
3.- Tell me which versions of IOS and Android you are using and the phone models.

Hopefully with this I can reproduce it and give you more insight. ;)

**Comment by Amrazyan** [comment]
Hi @Flucadetena , sorry for late reply, I will try to create example app, and share with you as soon as possible

**Comment by Flucadetena** [comment]
@Amrazyan Awesome thanks! No worries, taking the time you need, no hurry ;)

**Comment by Flucadetena** [comment]
Hey @Amrazyan any news on this? Where you able to find any new information??

**Comment by Amrazyan** [comment]
Hi @Flucadetena [https://we.tl/t-zcmB9J6Utz](url) , Im sharing with you an example app,it is the simple representation of my real project.
The issue still happens for example in Iphone 15 pro 256 gb,I didnt reset my phone, I can sometimes shake it, use it during the day , the issue appears mainly when opening app and start to get datas, but for example if I open app and get data on every 15 seconds, it gives me normal values
3. previously I used IOS version 17.5.1 now Im in IOS 18.0 Beta version

**Comment by Flucadetena** [comment]
Hi @Amrazyan I'm not sure why but i cant open the link. Could you please share the repo of the project with me? or create a new repo in git and share it please?

**Comment by Flucadetena** [comment]
Hey @Amrazyan If you find a way to send me the code to test or get new info, feel free to comment or reopen the issue. Hope it worked out in the end ;)
